### PR TITLE
fix: update install.sh - add line 'git pull --ff-only'

### PR DESCRIPTION
**Pull request by freddyp92**
## Description
Added the line `git pull -ff-only` after `git checkout` in install.sh.

## Motivation and Context
Ensures the develop branch is up-to-date on the machine the development environment is being installed on.

## How Has This Been Tested?
Tested locally on my machine.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sublimino** [comment]
The selection of `git` commands at [L92-L97](https://github.com/UKHomeOffice/development_environment/blob/5561fc5e4b5ac1beb3060d7b9d1f37556646bd38/ansible/install.sh#L92-L97) should ensure the checkout HEAD is also the remote HEAD.

Has this failed in testing?

**Comment by freddyp92** [comment]
@sublimino this fix was discussed with @SamFrier as without the `git pull --ff-only` there is a chance the local repository will be behind the develop branch.
I forked the development_environment repo and added the line to the install.sh and it worked without failures.

**Comment by pixie79** [comment]
@sublimino can you please review this as I am not sure on the ordering.

**Comment by freddyp92** [comment]
If it is not clear why this line is required, here are some screenshots for clarification.

After running curl command for current install.sh
screenshot from 2017-01-19 10-50-59

After running curl command for install.sh with `git pull --ff-only` added after `git checkout ${TAG}`
screenshot from 2017-01-19 10-56-01

@pixie79 the ordering may need to be changed slightly (I'm not too sure to be honest), but I believe its important that the local repository is up to date with the origin/develop branch

**Comment by freddyp92** [comment]
To clarify this further, this is only a problem when the machine running the curl command has already ran it before and therefore the /opt/GIT/development_environment directory already exists. Deleting this local repository before running the curl command also ensures that the branch is up to date with the latest develop branch.

**Comment by sublimino** [comment]
Thanks for the updates @freddyp92 - that makes sense now.

I've proposed an alternative solution in https://github.com/UKHomeOffice/development_environment/pull/76 that reduces the complexity of git commands - I'll leave this open for discussion/in case the other doesn't function as expected.

**Comment by pixie79** [comment]
probably no longer required after sublimino changes

**Pull request closed without merging**
