### PR TITLE
Modified docker and firewall ansible roles have been applied. See Jir…

### PR DESCRIPTION
**Pull request by shazChaudhry**
…a tikets: CROSSING-7064; CROSSING-7065; CROSSING-7067; CROSSING-7069; CROSSING-7336 and https://github.com/UKHomeOffice/ansible-base-role/pull/43

### CODE REVIEW

**Comment by fosuoy** [comment]
test

**Review by sirv1ne — COMMENTED** [review]
Have there been any changes to the modules in the GUI Role?

**Review by fosuoy — APPROVED** [review]

**Comment by fosuoy** [comment]
@sirv1ne - when changes are made to the GUI role another pull request can be made?

**Comment by sirv1ne** [comment]
@fosuoy Sure, that makes sense and is a little more auditable. Just wanted to make sure all of the changes made to the roles have been accounted for :)

**Comment by shazChaudhry** [comment]
reference to all changes that i am aware of are provided in the commit comments. feel free to take a look

**Review by sirv1ne — APPROVED** [review]
LGTM

**Pull request merged**
